# Site settings
title: "Realitix's blog"
email: realitix@gmail.com
description: "Technical blog about things I like"
baseurl: ""
url: "https://js78.github.io"
title_description: '"There are 10 types of people in the world: those who understand binary, and those who don''t."'
title_image: "/img/avatar.png"
github_repository: https://github.com/js78
post_limit: 20

# Social usernames/URLs
twitter_username: realitix
github_username:  realitix

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
